### ISSUE TITLE
cuspaceflight / Squirrel-Log 

### ISSUE THREAD

**Issue by jakubczaplicki** [jakubczaplicki/iTesa#10]
Interesting how simple their app was : https://github.com/cuspaceflight/Squirrel-Log/tree/master/src/uk/ac/cam/cusf/squirrellog

Note the fact that the logging function runs as a service, and that they register sensor listeners inside this service.

**Comment by ghost** [comment]
Do you think recording the data as logs and reading them in to perform analysis, after the fact, is the way to go?
