### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by jakubczaplicki** [jakubczaplicki/iTesa#11]
I just had a though that drawing such plot http://www.nasa.gov/centers/goddard/images/content/95391main_globe_m.jpg as the background would be very interesting. Assuming that the app is going to run for a time long enough so that the satellite "covers" the whole earth. I guess we could simply put a grayscale map of the Earth as the background and then change the colours of the pixels on the bitmap every N minutes (or so) and refresh the background.

**Comment by ghost** [comment]
We want the final picture to be visually striking.  This would be a good extension to iTesa, but is outside the scope of what we initially said it would do.  What is curious is that the measurements are back to the order of 20nT
