### ISSUE TITLE
App behaviour 

### ISSUE THREAD

**Issue by jakubczaplicki** [jakubczaplicki/iTesa#2]
What to do onDestroy, onStop, onPause, onResume ?
What do we need to do in order to close/finish app properly ?

**Comment by ghost** [comment]
We need to unregister all listeners and close io streams and ensure data is saved.

Also releasing any Wakelock/screenlocks.

Have you seen the Activity Lifecycle diagram?
http://www.skill-guru.com/blog/2011/01/13/android-activity-life-cycle/

If you notice, onPause comes before Stop or Destroy.  So we can do everything we need to do there and it would cover the other cases.  Then restart whatever we need to in onStart/Restart/Resume - which I think we would have to do anyway.

**Comment by jakubczaplicki** [comment]
I just analysed this life cycle based on what happens when another activity is opened. In our case - the preferences activity (I merged the branch with menu and preferences). I've added debug logs to all the onFunctions - logs help a lot to see what's going on. Run the app, go to DDMS in eclipse and set filter "by Log Tag" : iTesa.

**Comment by ghost** [comment]
Will need to get on with the logging business.

Had a thought in the meantime.  Other than the obvious close listeners etc (good citizen stuff); we need to write the picture/graph/iTesa to a file so it can be sent back. 

The real question, and we will find out on 5th, is how they intend to trigger the app closure.  (And I suppose whether they intend to use it more than once).

**Comment by jakubczaplicki** [comment]
True true. I asked the guy from the Cambridge Uni team how they logged their data on http://www.cusf.co.uk/squirrel/2.0/ (no reply yet).

We could take a screen-shot of the app and save it :)

Re. Triggering app closure: it's possible to control it from the console (aka ADB or SSH). That includes installation, so I guess it is possible to upgrade the app if we find bugs after deployment.

**Comment by ghost** [comment]
I suspect the Cambridge guys read the data on the phone when they recovered it. :)

I'm wondering if sending the data back would actually use less memory... but I do like the idea of getting a picture.
