### ISSUE TITLE
Activity restarted after screen rotation

### ISSUE THREAD

**Issue by jakubczaplicki** [jakubczaplicki/iTesa#3]
We could simply block the landscape mode.
Or we could show values in portrait mode and plot graph in landscape mode.

**Comment by ghost** [comment]
I think it's best to just keep it in Landscape mode.  I don't know how stable it is, but the camera is pointing towards Earth which means it is at the worst orientation w.r.t adjusting which orientation it is in.  Flipping between modes causes pauses in sensors which I suspect we don't wish to interrupt.

I had some code which was supposed to take care of this but it wasn't working properly.  If you're happy then I can add the task to the wiki (keep screen orientation locked) for me to do - it's something I had partially done anyway.

**Comment by jakubczaplicki** [comment]
Locking activity to orientation is easy. O did this by simply adding a parameter android:screenOrientation (e.g. android:screenOrientation="portrait")  to the activity in the AndroidManifest.xml

**Comment by ghost** [comment]
Interesting.  This worked for some apps I did, but specifically not for the one which uses the Orientation Sensor.  My assumption was that registering an event listened (of any kind) would disrupt it; evidently it is just the O-Sensor.  That's good news.

Are you happy with keeping it landscape?  We can (legitimately ;) close the issue.
