### ISSUE TITLE
Questions for STRaND

### ISSUE THREAD

**Issue by ghost** [jakubczaplicki/iTesa#6]
Is this the correct place to do this?  If you think the wiki would be better then close and move there.

But we really should start thinking up the key questions we need answered by STRaND.  They are going to throw a lot of info at us, so organising our thoughts beforehand will be crucial.

**Comment by jakubczaplicki** [comment]
I like the issues feature. It allows us to remember on what to do :) 

One thing I was thinking of was that they said they they are going to communicate with the phone via wi-fi. So does it mean we should implement an interface for controlling our app ? E.g. open socket, wait for a command "start", "stop", "set resolution=10", etc. etc. ? Unless they are thinking of using http://developer.android.com/guide/developing/tools/monkeyrunner_concepts.html which would then require writing monkeyrunner script (easy job).

Let's not forget that "If you have anything you specifically want covered in the workshop, or have technical questions in the mean time, please can I ask you to email them to both me and Dr. Chris Bridges (c.p.bridges@surrey.ac.uk), and we can compile and feed them in to the workshop material."

**Comment by ghost** [comment]
This monkeyrunner seems like an absolutely ideal way to do things.

It might be a good idea to implement an interface anyway. Or - just thinking aloud here - putting an interface on the app functionality.  Okay, so this would probably seem the same as what you suggest, but I am thinking in terms of separating out the measurement and data analysis parts for future use.

I'm going to look into wifi.
