### ISSUE TITLE
Just a note on data

### ISSUE THREAD

**Issue by jakubczaplicki** [jakubczaplicki/iTesa#8]
MAGSAT data : "Description: 0.5-sec. resolution magnetic field vectors from NASA's MAGSAT spacecraft (300-600 km altitude, 90 deg inclination) taken between November 2, 1979 and May 6,1980. "

Selected parameters:
 1 Geocentric Lat.
 2 Geocentric Long.
 3 Radial distance
 4 Bx,nT, NEV
 5 By, nT, NEV
 6 Bz, nT, NEV
 7 Flag

MILLISEC       1        2         3        4        5        6     7 
   14181   68.296 -111.378  6881.902   3572.7   2101.3  47224.9  1022
   14672   68.326 -111.406  6881.914   3562.6   2100.6  47222.1     0
   15164   68.355 -111.435  6881.922   3552.6   2101.2  47220.2     0
   15655   68.384 -111.464  6881.934   3545.8   2099.4  47217.2     0
   16147   68.414 -111.493  6881.949   3536.5   2100.4  47215.3     0
   16638   68.443 -111.523  6881.961   3528.2   2100.9  47213.3     0
   17130   68.472 -111.552  6881.969   3518.9   2100.5  47211.4     0
   17621   68.502 -111.581  6881.980   3512.3   2100.1  47208.3     0
   18113   68.531 -111.610  6881.992   3502.7   2100.7  47206.4     0
   18604   68.560 -111.640  6882.004   3495.3   2099.4  47204.6     0
   19096   68.589 -111.669  6882.016   3486.6   2100.6  47202.5     0
   19587   68.619 -111.699  6882.027   3478.2   2099.6  47199.6     0

**Comment by ghost** [comment]
The first one has a magnitude of 8033.69nT which is way above what I was expecting.  This is very good news, as it means it's less likely that the phone will interfere (i.e. the signal to noise ratio would be better).

I'm rethinking the way to do the colours on the graph via the data analysis.  Going to see if any other issues mention this, else I'll put it here.
